FROM adoptopenjdk:15-jdk-hotspot

# Setup adapted from https://github.com/hseeberger/scala-sbt/blob/master/debian/Dockerfile
RUN \
  apt-get update -q && \
  apt-get upgrade -qq && \
  apt-get install -y git && \
  rm -rf /var/lib/apt/lists/*

# Any RUN command after an ARG is set has that value in it as an environment variable and thus
# invalidates layer cache, so only declaring these ARGs when they're used

# Set up coursier, sbt, scala
RUN \
  cd /usr/local/bin && \
  curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)" && \
  chmod +x cs && \
  ./cs setup -y

WORKDIR /app

ADD project *.sbt src /app/

RUN sbt compile
